### ISSUE TITLE
rust inlay_hints doesn't work as aucmd

### ISSUE THREAD

**Issue by abdellatif-temsamani** [tjdevries/lsp_extensions.nvim#34]
i get this  error :
`Error detected while processing BufWinEnter Autocommands for "*.rs"`

when i added this:

```vim
au BufEnter,BufWinEnter,TabEnter *.rs :lua require'lsp_extensions'.inlay_hints{ prefix = ' » ', highlight = 'Comment', enabled = {'ChainingHint'} }
```

but when i run:
```vim
lua require'lsp_extensions'.inlay_hints{ prefix = ' » ', highlight = 'Comment', enabled = {'ChainingHint'} }

" it works fun
```

**Comment by luisvgs** [comment]
I'm dealing with the same error. Did you were able to solve it by any chance? Thanks in advance.

**Comment by abdellatif-temsamani** [comment]
> I'm dealing with the same error. Did you were able to solve it by any chance? Thanks in advance.

I couldn't get it to work, If you keep running manually it would work I guess

**Comment by felipesere** [comment]
I'm pretty sure the problem is that when `BufEnter` , `BufWinEnter` run for the first time there is no LSP setup at the time.
I wonder if loading can be delayed in `.inlay_hints` or in the autocmd.

I've just tested this on a fork with a 10ms delay and it then works as expected.

Edit:
I was able to make this work as expect with the following changes to my dotfiles:
Install `  Plug 'norcalli/nvim_utils'` to autocmds in lua.
Add the following to the `on_attach` callback that kicks in for LSPs:
```lua
  INLAY_HINTS = {
  	set = function()
      local lsp_extensions = require('lsp_extensions');
      lsp_extensions.inlay_hints { prefix = '', alinged = true, highlight = "TypeHighlight", enabled = { "TypeHint", "ChainingHint", "ParameterHint"} };
    end;
  }
  
  local autocmds = {
    highlighting = {
      {"CursorMoved",  "*", "lua INLAY_HINTS.set()" },
      {"InsertLeave",  "*", "lua INLAY_HINTS.set()" },
      {"BufEnter",     "*", "lua INLAY_HINTS.set()" },
      {"BufWinEnter",  "*", "lua INLAY_HINTS.set()" },
      {"TabEnter",     "*", "lua INLAY_HINTS.set()" },
      {"BufWritePost", "*", "lua INLAY_HINTS.set()" },
    },
  }
  require('nvim_utils')
  nvim_create_augroups(autocmds)
```

That way, the inlay hints only get attached when the LSP server (Rust analzyer) is started. ✌️

**Comment by abdellatif-temsamani** [comment]
thank you, it's working fine
